### ISSUE TITLE
"Couldn't get new vault. Try again?"

### ISSUE THREAD

**Issue by JacobDB** [dfrankland/hyperterm-lastpass#2]
I can't seem to log in. I've verified my password like 8 times, not sure what's up. I do have 2FA turned on, but it sounds like from your README that that's supported... Hmm.

EDIT: sorry to bug you on two separate projects, haha.

**Comment by JacobDB** [comment]
Nevermind! I'm using the LastPass app for 2FA, and apparently I had to very quickly approve the login before the extension timed out the login. Weird.

**Comment by dfrankland** [comment]
👍
